### ISSUE TITLE
Unable to close share screen on iPhone with version 8.2.3

### ISSUE THREAD

**Issue by ASankey-Ideagen** [PSPDFKit/Appcelerator-iOS#28]
Using v8.2.3

Titanium SDK - 8.0.1.GA
Xcode 10.2.1
iOS 12

- Whilst using an iPhone device, open a pdf and click on share.
- Tapping close has no affect and share screen will remain open.
- Tapping 'Share' button also not opening sharing options. Preparing dialog shows, but nothing happens after.

This also affect Email and Print options.

Works as expected on iPad devices.

**Comment by radazzouz** [comment]
@ASankey-Ideagen,

We've had several fixes and improvements for our document sharing API since version 8.2.3. Please update to the latest stable version and let me know if this happens still.

This doesn't look like an Appcelerator bindings issue. For such requests, please reach out to our support portal at pspdfkit.com/support/request/, this will guarantee faster response times and a better and more streamlined support experience.

Thank you!

**Comment by ASankey-Ideagen** [comment]
@radazzouz 

This is still happening with the latest 8.4.0 framework.
Module was built using latest master along with the 8.4.0 binary build frameworks following the steps within the readme.

Building the latest natively works as expected, so appears to be a Titanium issue.

**Comment by hansemannn** [comment]
Stepping in here to check if Titanium is the issue. Would you mind trying with 8.0.2.GA?

**Comment by ASankey-Ideagen** [comment]
Issue still there when build with 8.0.2.GA.

**Comment by radazzouz** [comment]
@hansemannn, thank you for the assist!

@ASankey-Ideagen, thank you for the additional information.

So far we know that this is not a native issue, since it works in PSPDFKit for iOS when using it outside Titanium.

Can you try using the share sheet in a Titanium app without using PSPDFKit? This will help us determine if this is a bindings issue.

Thanks again!

**Comment by ASankey-Ideagen** [comment]
@radazzouz 

Using TiSocial.Framework I am able to show the share sheet successfully.
I think this has more to do with the window that is being shown first than with the share sheet itself.
I've attached a screenshot showing the screen that cannot be closed.

As previously mentioned, on iPad the functionality works as expected, including opening the share sheet upon tapping 'Share'

![Simulator Screen Shot - iPhone 6s - 2019-06-21 at 12 43 53](https://user-images.githubusercontent.com/50233322/59920402-51948e80-9422-11e9-96b5-cf3eba9ffdd4.png)

**Comment by OscarSwanros** [comment]
@ASankey-Ideagen — we're unable to reproduce this on our side. 

![recording](https://user-images.githubusercontent.com/629157/59932506-eee4c800-940c-11e9-83db-a4047060176c.gif)

Does `TiSocial.Framework` itself present the PSPDFKit Sharing Interface? That could be an issue if the internal delegates are not setup correctly to handle success and closing commands from the UI. Would you mind sending us a GIF with a demo of the issue and how it looks so we can get a better idea of the setup here? 

Thanks.

**Comment by ASankey-Ideagen** [comment]
Use of TiSocial.Framework was just to verify that the share sheet could be opened by something other than PSPDFKit as requested by @radazzouz .

The attached gif demonstrates what we are experiencing within our app.
![PSPDFKit ShareIssue](https://user-images.githubusercontent.com/50233322/60001788-277be000-965f-11e9-9a7d-9156aef3c201.gif)

Could this be an environment issue when building the Ti package?

**Comment by OscarSwanros** [comment]
Thank you! There's not much I can gather from the GIF, unfortunately, but the behavior here would point me to thinking that the delegates are not being correctly set on the sharing controller, or some how the sharing configuration is being messed up with.

Could you share a code snippet of how you're configuring PSPDFKit? I'm specially interested in the options object that's passed as part of the initialization.

**Comment by ASankey-Ideagen** [comment]
I've used the following code to display the pspdfkit view, however, I've also tried with the examples given within this repository and the issue is still occurs within them too.

```
function loadAttachement(filename){
	docView = Alloy.pspdfkit.createView({
		options : {
			pageMode : 2
		},
		filename : filename
	});
	
	$.canvas.add(docView);
}

loadAttachement('PSPDFKit.pdf');

$.index.open();
```

**Comment by radazzouz** [comment]
Hi @ASankey-Ideagen,

I am sorry for the delay in responding.

I just retested this issue with the upcoming changes from #29 and it has been fixed.

![recording](https://user-images.githubusercontent.com/7443038/68676666-7e0f8b00-0528-11ea-8c51-520ef99f1c95.gif)

Can you please update to the new version and let us know if upgrading solved the issue?

I am closing this issue for now.

Once again, thank you for reporting.

**Comment by akashivskyy** [comment]
I see this is still happening on iOS 12, unfortunately. Looks like an issue on Titanium side.
